# Generated by Django 6.0.5 on 2026-06-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')], default=3, null=True),
        ),
    ]
